###Pandas Series: The Building Block of Data Analysis

**A Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floats, Python objects, etc.).**

It has two main components:


*   values: The actual data (like a NumPy array)
*   index: Labels for each element (like row names)

In [ ]:
# Creating a Series

import pandas as pd

# Basic series (default integer index)
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
s

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
# With Custom Index

s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s)

a    10
b    20
c    30
dtype: int64

In [ ]:
#  From a Dictionary
data = {'apple': 5, 'banana': 3, 'cherry': 8}
s = pd.Series(data)
print(s)

apple     5
banana    3
cherry    8
dtype: int64

In [ ]:
# From a Scalar (Broadcasting)
s = pd.Series(5, index=['x', 'y', 'z'])
print(s)

x    5
y    5
z    5
dtype: int64

In [ ]:
# Key Properties

s = pd.Series([1, 2, 3], index=['x', 'y', 'z'])
print(s.values)
print(s.index)

[1 2 3]
Index(['x', 'y', 'z'], dtype='object')

In [ ]:
s

x    1
y    2
z    3
dtype: int64

In [ ]:
# Accessing Elements
# By Position (Integer Location)

s = pd.Series([10, 20, 30, 40,50], index=['a', 'z','b', 'c', 'd'])
print(s)
print(s[0])      # 10 (first element)
print(s.iloc[2]) # 30 (explicit integer location)

a    10
z    20
b    30
c    40
d    50
dtype: int64
10
30

/tmp/ipython-input-2030083781.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])      # 10 (first element)

In [ ]:
# By Label (Index)

print(s['b'])    # 20
print(s.loc['c'])# 30 (explicit label-based access)

20
30

In [ ]:
# Slicing
print(s['a':'c'])   # Includes 'c'! → ['a', 'b', 'c']
print(s[0:3])

a    10
z    20
b    30
c    40
dtype: int64
a    10
z    20
b    30
dtype: int64

In [ ]:
# . Vectorized Operations

import numpy as np
s = pd.Series([1, 2, 3, 4])

# Arithmetic
print(s + 10)    # [11, 12, 13, 14]
print(s * 2)     # [2, 4, 6, 8]

# Math functions
print(s ** 2)    # [1, 4, 9, 16]
print(np.sqrt(s))# [1.0, 1.414, 1.732, 2.0]

# Boolean masking
print(s > 2)     # [False, False, True, True]
print(s[s > 2])  # [3, 4]

0    11
1    12
2    13
3    14
dtype: int64
0    2
1    4
2    6
3    8
dtype: int64
0     1
1     4
2     9
3    16
dtype: int64
0    1.000000
1    1.414214
2    1.732051
3    2.000000
dtype: float64
0    False
1    False
2     True
3     True
dtype: bool
2    3
3    4
dtype: int64

In [ ]:
# Boolean masking
print(s > 2)     # [False, False, True, True]


# s[s>2]
print(s[s > 2])  # [3, 4]

0    False
1    False
2     True
3     True
dtype: bool
2    3
3    4
dtype: int64

In [ ]:
# Alignment: The Magic Feature
# When operating on two Series, Pandas aligns by index:


s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])



s2 = pd.Series([10, 20, 30], index=['b', 'c', 'd'])

print(s1 + s2)

a     NaN
b    12.0
c    23.0
d     NaN
dtype: float64

In [ ]:
s = s1 + s2
s

a     NaN
b    12.0
c    23.0
d     NaN
dtype: float64

In [ ]:
s.fillna(0)

a     0.0
b    12.0
c    23.0
d     0.0
dtype: float64

In [ ]:
s = pd.Series([1, 2, np.nan, 4,4])
s
print(s.fillna(0))      # [1, 2, 0, 4]
print(s.value_counts()) # Counts non-null values

0    1.0
1    2.0
2    0.0
3    4.0
4    4.0
dtype: float64
4.0    2
1.0    1
2.0    1
Name: count, dtype: int64

In [ ]:
s

0    1.0
1    2.0
2    NaN
3    4.0
4    4.0
dtype: float64

In [ ]:
dates = pd.date_range('2025-01-01', periods=5)
prices = pd.Series([100, 102, 101, 105, 107], index=dates)

print(prices)


print(prices['2025-01-03'])  # 101
print(prices.pct_change())   # Daily % change

2025-01-01    100
2025-01-02    102
2025-01-03    101
2025-01-04    105
2025-01-05    107
Freq: D, dtype: int64
101
2025-01-01         NaN
2025-01-02    0.020000
2025-01-03   -0.009804
2025-01-04    0.039604
2025-01-05    0.019048
Freq: D, dtype: float64

###Pandas DataFrame: The Heart of Data Science in Python

**A DataFrame is a 2-dimensional labeled data structure with:**


*   Rows (indexed by labels)
*   Columns (each with a name and data type)
* Can hold heterogeneous data (integers, floats, strings, booleans, etc.)

In [ ]:
# Creating a DataFrame
# From a Dictionary

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Tokyo']
}

df = pd.DataFrame(data)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo

In [ ]:
# From a List of Dictionaries
data = [
    {'Name': 'Alice', 'Age': 25},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'}
]
df = pd.DataFrame(data)
# Missing values become NaN
df

    Name  Age    City
0  Alice   25     NaN
1    Bob   30  London

In [ ]:
adults = df[df['Age'] > 25]
adults

  Name  Age    City
1  Bob   30  London

In [ ]:
df["Name"]

In [ ]:
df['Country'] = ['USA', 'UK']
df['Is_Adult'] = df['Age'] >= 18
df

    Name  Age    City Country  Is_Adult
0  Alice   25     NaN     USA      True
1    Bob   30  London      UK      True

In [ ]:
# df.drop('Country', axis=1, inplace=True)  # axis=1 → columns
# OR
del df['Country']

In [ ]:
df

    Name  Age    City  Is_Adult
0  Alice   25     NaN      True
1    Bob   30  London      True

In [ ]:
# Renaming Columns

In [ ]:
# From NumPy Arrays
import numpy as np
arr = np.random.randn(4, 3)
print(arr)
df = pd.DataFrame(arr, columns=['A', 'B', 'C'], index=['w', 'x', 'y', 'z'])
df

[[-0.34498355 -1.35810143  1.79510484]
 [-0.97455927 -0.14979176 -1.85824445]
 [ 0.10175708 -1.17264609  0.06751516]
 [-0.11349386  2.5518361   1.46838531]]

          A         B         C
w -0.344984 -1.358101  1.795105
x -0.974559 -0.149792 -1.858244
y  0.101757 -1.172646  0.067515
z -0.113494  2.551836  1.468385

In [ ]:
print(df.shape)
print(df.columns)
print(df.dtypes)

(4, 3)
Index(['A', 'B', 'C'], dtype='object')
A    float64
B    float64
C    float64
dtype: object

In [ ]:
first_row = df.iloc[0]          # First row (Series)
first_two = df.iloc[0:2]        # First two rows (DataFrame)
specific = df.iloc[[0, 2], [0, 2]]  # Rows 0,2 and cols 0,2

In [ ]:
specific

          A         C
w -0.344984  1.795105
y  0.101757  0.067515

In [ ]:
first_two

          A         B         C
w -0.074722  0.349004  1.464683
x  1.096069  1.504674 -1.080692

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, w to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      float64
 2   C       4 non-null      float64
dtypes: float64(3)
memory usage: 300.0+ bytes

In [ ]:
! pip install dash --q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 103.8 MB/s eta 0:00:00

In [ ]:
# Run this app with `python app.py` and
# visit http://127.0.0.1:8050/ in your web browser.


from dash import Dash, html, dcc
import plotly.express as px
import pandas as pd

app = Dash()

# assume you have a "long-form" data frame
# see https://plotly.com/python/px-arguments/ for more options
df = pd.DataFrame({
    "Fruit": ["Apples", "Oranges", "Bananas", "Apples", "Oranges", "Bananas"],
    "Amount": [4, 1, 2, 2, 4, 5],
    "City": ["SF", "SF", "SF", "Montreal", "Montreal", "Montreal"]
})

fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")

app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for your data.
    '''),

    dcc.Graph(
        id='example-graph',
        figure=fig
    )
])

if __name__ == '__main__':
    app.run(debug=True)

Dash is running on http://127.0.0.1:8050/

INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__'
 * Debug mode: on